// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe8lAytFzSUGCgJllRqwZzAwLrT0Ngrh8',
    appId: '1:367804537019:web:3ec8c9a3e1abd45de9319e',
    messagingSenderId: '367804537019',
    projectId: 'crudapp-1d1e5',
    authDomain: 'crudapp-1d1e5.firebaseapp.com',
    storageBucket: 'crudapp-1d1e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb2ghNmg-Zsc8i738vyA7ubHLsn1SYeEE',
    appId: '1:367804537019:android:fe2b60e08cf9623ce9319e',
    messagingSenderId: '367804537019',
    projectId: 'crudapp-1d1e5',
    storageBucket: 'crudapp-1d1e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxECUR-9HfmcFwP5S-w13jAc3gp6yVUc',
    appId: '1:367804537019:ios:8f0568f0f1ed5256e9319e',
    messagingSenderId: '367804537019',
    projectId: 'crudapp-1d1e5',
    storageBucket: 'crudapp-1d1e5.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKxECUR-9HfmcFwP5S-w13jAc3gp6yVUc',
    appId: '1:367804537019:ios:f727bd699837d6e7e9319e',
    messagingSenderId: '367804537019',
    projectId: 'crudapp-1d1e5',
    storageBucket: 'crudapp-1d1e5.appspot.com',
    iosBundleId: 'com.example.connectify.RunnerTests',
  );
}
